# -*- coding: utf-8 -*-
"""project ntiii

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhGBGQRgMyXTenHtJXJIBBH9A3xPetA5
"""

# ============================================================
# CUSTOMER SHOPPING ANALYSIS
# Customer Segmentation + Classification
# ============================================================


# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

from sklearn.metrics import (
    silhouette_score,
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    precision_score,
    recall_score,
    f1_score
)

from sklearn.model_selection import (
    train_test_split,
    cross_val_score
)

from sklearn.pipeline import Pipeline

from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

import warnings
warnings.filterwarnings("ignore")

sns.set_style("whitegrid")

RANDOM_STATE = 42

# ============================================================
# 2. LOAD DATA
# ============================================================

df = pd.read_csv("/content/shopping_behavior_updated (1).csv")
print("\nFirst 5 rows:")
display(df.head())

print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("Dataset Information:\n")
df.info()

print("\nStatistical Summary:")
display(df.describe(include="all").T)

# ============================================================
# 4. DATA QUALITY CHECK
# ============================================================

print("Missing Values:")
display(df.isnull().sum())

print("\nTotal Missing Values:", df.isnull().sum().sum())

print("\nDuplicated Rows:")
print(df.duplicated().sum())

print("\nUnique Values:")
display(df.nunique().sort_values())

# ============================================================
# 5. REMOVE CUSTOMER ID
# ============================================================

if "Customer ID" in df.columns:
    df.drop(columns=["Customer ID"], inplace=True)

print("Customer ID removed.")
print("New shape:", df.shape)

# ============================================================
# 6. HANDLE EMPTY STRINGS
# ============================================================

df = df.replace(r"^\s*$", np.nan, regex=True)

print("Missing values after checking empty strings:")
display(df.isnull().sum())

print(df.dtypes)

# ============================================================
# 9. BASIC EDA
# ============================================================

# Age Distribution

plt.figure(figsize=(8,5))
sns.histplot(df["Age"], bins=20, kde=True)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Number of Customers")
plt.show()

# ============================================================
# 10. PURCHASE AMOUNT DISTRIBUTION
# ============================================================

plt.figure(figsize=(8,5))
sns.histplot(df["Purchase Amount (USD)"], bins=20, kde=True)
plt.title("Purchase Amount Distribution")
plt.xlabel("Purchase Amount (USD)")
plt.ylabel("Number of Customers")
plt.show()

# ============================================================
# 11. GENDER DISTRIBUTION
# ============================================================

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="Gender"
)

plt.title("Gender Distribution")
plt.xlabel("Gender")
plt.ylabel("Number of Customers")
plt.show()

# ============================================================
# 12. CATEGORY DISTRIBUTION
# ============================================================

plt.figure(figsize=(9,5))

sns.countplot(
    data=df,
    y="Category",
    order=df["Category"].value_counts().index
)

plt.title("Product Category Distribution")
plt.xlabel("Number of Customers")
plt.ylabel("Category")
plt.show()

# ============================================================
# 13. TOP PURCHASED ITEMS
# ============================================================

top_items = df["Item Purchased"].value_counts().head(15)

plt.figure(figsize=(10,6))

sns.barplot(
    x=top_items.values,
    y=top_items.index
)

plt.title("Top 15 Purchased Items")
plt.xlabel("Number of Purchases")
plt.ylabel("Item")
plt.show()

# ============================================================
# 14. SUBSCRIPTION STATUS
# ============================================================

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="Subscription Status"
)

plt.title("Subscription Status")
plt.xlabel("Subscription Status")
plt.ylabel("Number of Customers")
plt.show()

# ============================================================
# 15. DISCOUNT APPLIED
# ============================================================

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="Discount Applied"
)

plt.title("Discount Applied")
plt.xlabel("Discount Applied")
plt.ylabel("Number of Customers")
plt.show()

# ============================================================
# 16. FREQUENCY OF PURCHASES
# ============================================================

plt.figure(figsize=(10,5))

sns.countplot(
    data=df,
    y="Frequency of Purchases",
    order=df["Frequency of Purchases"].value_counts().index
)

plt.title("Frequency of Purchases")
plt.xlabel("Number of Customers")
plt.ylabel("Frequency")
plt.show()

# ============================================================
# 17. CORRELATION HEATMAP
# ============================================================

numeric_df = df.select_dtypes(include=np.number)

plt.figure(figsize=(10, 7))

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    fmt=".2f",
    center=0,
    cmap="coolwarm",  # أضفنا هذا اللون الاحترافي والمميز
    linewidths=0.5,  # أضفنا فواصل دقيقة بين المربعات لترتيب الشكل
)

plt.title("Correlation Heatmap")
plt.xticks(rotation=45, ha="right")  # تدوير أسماء المحاور لتكون واضحة
plt.show()

# ============================================================
# 18. OUTLIERS CHECK
# ============================================================

outlier_columns = [
    "Age",
    "Purchase Amount (USD)",
    "Review Rating",
    "Previous Purchases"
]

plt.figure(figsize=(12,6))

sns.boxplot(
    data=df[outlier_columns]
)

plt.title("Outliers Check")
plt.xticks(rotation=45)
plt.show()

# ============================================================
# 19. FEATURE ENGINEERING
# ============================================================

# Convert Gender to binary

if "Gender" in df.columns:

    df["Gender_Binary"] = df["Gender"].map({
        "Male": 1,
        "Female": 0
    })

# Convert Yes/No columns to 0/1

binary_columns = [
    "Subscription Status",
    "Discount Applied"
]

for col in binary_columns:

    if col in df.columns:

        unique_values = set(df[col].dropna().unique())

        if unique_values.issubset({"Yes", "No"}):

            df[col] = df[col].map({
                "Yes": 1,
                "No": 0
            })

# ============================================================
# 20. FREQUENCY ENCODING
# ============================================================

frequency_mapping = {
    "Annually": 1,
    "Every 3 Months": 2,
    "Quarterly": 2,
    "Bi-Weekly": 3,
    "Fortnightly": 3,
    "Monthly": 4,
    "Weekly": 5
}

if "Frequency of Purchases" in df.columns:

    df["Frequency_Score"] = (
        df["Frequency of Purchases"]
        .map(frequency_mapping)
    )

print("Frequency encoding completed.")

display(
    df[
        ["Frequency of Purchases", "Frequency_Score"]
    ].head(10)
)

# ============================================================
# 21. CLUSTERING FEATURES
# ============================================================

cluster_features = [
    "Age",
    "Gender_Binary",
    "Purchase Amount (USD)",
    "Review Rating",
    "Previous Purchases"
]

X_cluster = df[cluster_features].copy()

print("Features used for clustering:")
print(cluster_features)

print("\nShape:", X_cluster.shape)

display(X_cluster.head())

# ============================================================
# 22. CHECK CLUSTERING FEATURES
# ============================================================

print("Missing values in clustering features:")

display(X_cluster.isnull().sum())

print("\nSummary:")
display(X_cluster.describe())

# ============================================================
# 23. STANDARDIZATION
# ============================================================

scaler_cluster = StandardScaler()

X_scaled = scaler_cluster.fit_transform(X_cluster)

print("Standardization completed.")

print("Scaled data shape:", X_scaled.shape)

# ============================================================
# 24. ELBOW METHOD
# ============================================================

inertia = []

K_range = range(2, 11)

for k in K_range:

    kmeans = KMeans(
        n_clusters=k,
        random_state=RANDOM_STATE,
        n_init=10
    )

    kmeans.fit(X_scaled)

    inertia.append(kmeans.inertia_)


plt.figure(figsize=(8,5))

plt.plot(
    K_range,
    inertia,
    marker="o"
)

plt.title("Elbow Method")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Inertia")
plt.xticks(K_range)

plt.show()

# ============================================================
# 25. SILHOUETTE SCORE
# ============================================================

silhouette_scores = []

for k in K_range:

    kmeans = KMeans(
        n_clusters=k,
        random_state=RANDOM_STATE,
        n_init=10
    )

    labels = kmeans.fit_predict(X_scaled)

    score = silhouette_score(
        X_scaled,
        labels
    )

    silhouette_scores.append(score)

    print(
        f"K = {k} | Silhouette Score = {score:.4f}"
    )


plt.figure(figsize=(8,5))

plt.plot(
    K_range,
    silhouette_scores,
    marker="o"
)

plt.title("Silhouette Score for Different K")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Silhouette Score")
plt.xticks(K_range)

plt.show()

# ============================================================
# 26. SELECT NUMBER OF CLUSTERS
# ============================================================

best_k_by_silhouette = K_range[
    np.argmax(silhouette_scores)
]

print(
    "Best K according to Silhouette Score:",
    best_k_by_silhouette
)

# ------------------------------------------------------------
# IMPORTANT:
# If the Elbow graph clearly indicates another K and that
# value is more interpretable from a business perspective,
# you can manually change SELECTED_K.
# ------------------------------------------------------------

SELECTED_K = best_k_by_silhouette

print("Selected K:", SELECTED_K)

# ============================================================
# 27. FINAL K-MEANS MODEL
# ============================================================

kmeans_final = KMeans(
    n_clusters=SELECTED_K,
    random_state=RANDOM_STATE,
    n_init=10
)

df["Customer Segment"] = kmeans_final.fit_predict(
    X_scaled
)

print("K-Means clustering completed.")

print("\nCustomers per segment:")
print(
    df["Customer Segment"]
    .value_counts()
    .sort_index()
)

# ============================================================
# 28. SEGMENT PROFILE
# ============================================================

segment_profile = (
    df
    .groupby("Customer Segment")[cluster_features]
    .mean()
)

segment_size = (
    df["Customer Segment"]
    .value_counts()
    .sort_index()
)

segment_profile["Customer Count"] = segment_size

segment_profile["Customer %"] = (
    segment_size / len(df) * 100
)

print("Customer Segment Profile:")

display(
    segment_profile.round(2)
)

# ============================================================
# 29. SEGMENT SIZE
# ============================================================

plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x="Customer Segment"
)

plt.title("Number of Customers per Segment")
plt.xlabel("Customer Segment")
plt.ylabel("Number of Customers")

plt.show()

# ============================================================
# 30. PURCHASE AMOUNT BY SEGMENT
# ============================================================

plt.figure(figsize=(8,5))

sns.barplot(
    data=df,
    x="Customer Segment",
    y="Purchase Amount (USD)",
    errorbar=None
)

plt.title("Average Purchase Amount by Segment")
plt.xlabel("Customer Segment")
plt.ylabel("Average Purchase Amount (USD)")

plt.show()

# ============================================================
# 31. PREVIOUS PURCHASES BY SEGMENT
# ============================================================

plt.figure(figsize=(8,5))

sns.barplot(
    data=df,
    x="Customer Segment",
    y="Previous Purchases",
    errorbar=None
)

plt.title("Average Previous Purchases by Segment")
plt.xlabel("Customer Segment")
plt.ylabel("Average Previous Purchases")

plt.show()

# ============================================================
# 32. AGE BY SEGMENT
# ============================================================

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="Customer Segment",
    y="Age"
)

plt.title("Age Distribution by Customer Segment")
plt.xlabel("Customer Segment")
plt.ylabel("Age")

plt.show()

# ============================================================
# 33. REVIEW RATING BY SEGMENT
# ============================================================

plt.figure(figsize=(8,5))

sns.barplot(
    data=df,
    x="Customer Segment",
    y="Review Rating",
    errorbar=None
)

plt.title("Average Review Rating by Segment")
plt.xlabel("Customer Segment")
plt.ylabel("Average Review Rating")

plt.show()

# ============================================================
# 34. PCA VISUALIZATION
# ============================================================

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

pca_df = pd.DataFrame(
    X_pca,
    columns=["PC1", "PC2"]
)

pca_df["Customer Segment"] = (
    df["Customer Segment"].values
)

print(
    "Explained variance ratio:",
    pca.explained_variance_ratio_
)

print(
    "Total explained variance:",
    pca.explained_variance_ratio_.sum()
)

# ============================================================
# 35. PCA SCATTER PLOT
# ============================================================

plt.figure(figsize=(9,6))

sns.scatterplot(
    data=pca_df,
    x="PC1",
    y="PC2",
    hue="Customer Segment",
    s=60
)

plt.title("Customer Segmentation using K-Means + PCA")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")

plt.show()

# ============================================================
# 36. SEGMENT INTERPRETATION
# ============================================================

print("Segment Profiles:")
display(segment_profile.round(2))

# ============================================================
# 37. FIND HIGH / LOW VALUES PER SEGMENT
# ============================================================

for segment in segment_profile.index:

    profile = segment_profile.loc[segment]

    print("\n" + "="*60)
    print(f"SEGMENT {segment}")
    print("="*60)

    print(
        f"Customer Count: {profile['Customer Count']:.0f}"
    )

    print(
        f"Customer Percentage: {profile['Customer %']:.2f}%"
    )

    print(
        f"Average Age: {profile['Age']:.2f}"
    )

    print(
        f"Average Purchase Amount: "
        f"{profile['Purchase Amount (USD)']:.2f}"
    )

    print(
        f"Average Previous Purchases: "
        f"{profile['Previous Purchases']:.2f}"
    )

    print(
        f"Average Review Rating: "
        f"{profile['Review Rating']:.2f}"
    )

# ============================================================
# 38. CLASSIFICATION
# ============================================================

# IMPORTANT:
# The target is created by K-Means.
#
# Classification goal:
# Predict the Customer Segment of a new customer.
#
# We intentionally use the same behavioral/demographic
# features used for segmentation because the classification
# model is intended to assign a new customer to an existing
# segment.

X_classification = df[cluster_features].copy()

y_classification = df["Customer Segment"].copy()

print("Classification Features:")
print(cluster_features)

print("\nTarget:")
print("Customer Segment")

print("\nX shape:", X_classification.shape)
print("y shape:", y_classification.shape)

# ============================================================
# 39. TRAIN TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X_classification,
    y_classification,
    test_size=0.20,
    random_state=RANDOM_STATE,
    stratify=y_classification
)

print("Training set:", X_train.shape)
print("Testing set :", X_test.shape)

# ============================================================
# 40. LOGISTIC REGRESSION
# ============================================================

logistic_model = Pipeline([
    (
        "scaler",
        StandardScaler()
    ),

    (
        "classifier",
        LogisticRegression(
            max_iter=1000,
            random_state=RANDOM_STATE
        )
    )
])

logistic_model.fit(
    X_train,
    y_train
)

logistic_pred = logistic_model.predict(
    X_test
)

print("Logistic Regression trained.")

# ============================================================
# 41. RANDOM FOREST
# ============================================================

rf_model = RandomForestClassifier(
    n_estimators=300,
    random_state=RANDOM_STATE,
    class_weight="balanced"
)

rf_model.fit(
    X_train,
    y_train
)

rf_pred = rf_model.predict(
    X_test
)

print("Random Forest trained.")

# ============================================================
# 42. SVM
# ============================================================

svm_model = Pipeline([
    (
        "scaler",
        StandardScaler()
    ),

    (
        "classifier",
        SVC(
            random_state=RANDOM_STATE
        )
    )
])

svm_model.fit(
    X_train,
    y_train
)

svm_pred = svm_model.predict(
    X_test
)

print("SVM trained.")

# ============================================================
# 43. EVALUATION FUNCTION
# ============================================================

def evaluate_model(model_name, y_true, y_pred):

    accuracy = accuracy_score(
        y_true,
        y_pred
    )

    precision = precision_score(
        y_true,
        y_pred,
        average="macro",
        zero_division=0
    )

    recall = recall_score(
        y_true,
        y_pred,
        average="macro",
        zero_division=0
    )

    f1 = f1_score(
        y_true,
        y_pred,
        average="macro",
        zero_division=0
    )

    print("\n" + "="*60)
    print(model_name)
    print("="*60)

    print(f"Accuracy : {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall   : {recall:.4f}")
    print(f"F1 Score : {f1:.4f}")

    print("\nClassification Report:\n")

    print(
        classification_report(
            y_true,
            y_pred,
            zero_division=0
        )
    )

    return {
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1
    }

# ============================================================
# 44. MODEL EVALUATION
# ============================================================

results = []

results.append(
    evaluate_model(
        "Logistic Regression",
        y_test,
        logistic_pred
    )
)

results.append(
    evaluate_model(
        "Random Forest",
        y_test,
        rf_pred
    )
)

results.append(
    evaluate_model(
        "SVM",
        y_test,
        svm_pred
    )
)

# ============================================================
# 45. MODEL COMPARISON
# ============================================================

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="F1 Score",
    ascending=False
)

display(
    results_df.round(4)
)

# ============================================================
# 46. MODEL COMPARISON VISUALIZATION
# ============================================================

comparison_plot = results_df.set_index("Model")

comparison_plot[
    ["Accuracy", "Precision", "Recall", "F1 Score"]
].plot(
    kind="bar",
    figsize=(11,6)
)

plt.title("Classification Model Comparison")
plt.ylabel("Score")
plt.ylim(0, 1.05)
plt.xticks(rotation=0)

plt.legend(
    bbox_to_anchor=(1.02, 1),
    loc="upper left"
)

plt.show()

# ============================================================
# 47. SELECT BEST MODEL
# ============================================================

best_model_name = results_df.iloc[0]["Model"]

print("Best Model:", best_model_name)

if best_model_name == "Logistic Regression":

    best_model = logistic_model
    best_pred = logistic_pred

elif best_model_name == "Random Forest":

    best_model = rf_model
    best_pred = rf_pred

else:

    best_model = svm_model
    best_pred = svm_pred

# ============================================================
# 48. CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    best_pred
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm
)

fig, ax = plt.subplots(figsize=(8,6))

disp.plot(
    ax=ax
)

plt.title(
    f"Confusion Matrix - {best_model_name}"
)

plt.show()

# ============================================================
# 49. CROSS VALIDATION
# ============================================================

models = {
    "Logistic Regression": logistic_model,
    "Random Forest": rf_model,
    "SVM": svm_model
}

cv_results = []

for name, model in models.items():

    scores = cross_val_score(
        model,
        X_classification,
        y_classification,
        cv=5,
        scoring="f1_macro"
    )

    cv_results.append({
        "Model": name,
        "CV Mean F1": scores.mean(),
        "CV Std": scores.std()
    })

    print(
        f"{name}: "
        f"Mean F1 = {scores.mean():.4f}, "
        f"Std = {scores.std():.4f}"
    )

cv_results_df = pd.DataFrame(cv_results)

display(
    cv_results_df.round(4)
)

# ============================================================
# 50. RANDOM FOREST FEATURE IMPORTANCE
# ============================================================

feature_importance = pd.DataFrame({
    "Feature": cluster_features,
    "Importance": rf_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

display(
    feature_importance.round(4)
)

# ============================================================
# 51. FEATURE IMPORTANCE VISUALIZATION
# ============================================================

plt.figure(figsize=(9,5))

sns.barplot(
    data=feature_importance,
    x="Importance",
    y="Feature"
)

plt.title("Random Forest Feature Importance")
plt.xlabel("Importance")
plt.ylabel("Feature")

plt.show()

# ============================================================
# 52. FINAL CUSTOMER SEGMENT PROFILE
# ============================================================

final_profile = (
    df.groupby("Customer Segment")[cluster_features]
    .agg(["mean", "median"])
)

display(final_profile.round(2))

# ============================================================
# 53. PREDICT CUSTOMER SEGMENT FOR NEW CUSTOMER
# ============================================================

# Example new customer
#
# You can change these values to test different customers.

new_customer = pd.DataFrame({
    "Age": [30],
    "Gender_Binary": [1],
    "Purchase Amount (USD)": [75],
    "Review Rating": [4.5],
    "Previous Purchases": [20]
})

print("New Customer:")
display(new_customer)

# ============================================================
# 54. PREDICT CUSTOMER SEGMENT
# ============================================================

predicted_segment = best_model.predict(
    new_customer
)

print(
    "Predicted Customer Segment:",
    predicted_segment[0]
)

# ============================================================
# 55. SHOW PREDICTED SEGMENT PROFILE
# ============================================================

segment_number = predicted_segment[0]

print(
    f"New customer belongs to Segment {segment_number}"
)

print("\nSegment Characteristics:")

display(
    segment_profile.loc[[segment_number]].round(2)
)

# ============================================================
# 56. CUSTOMER SEGMENT PREDICTION FUNCTION
# ============================================================

def predict_customer_segment(
    age,
    gender,
    purchase_amount,
    review_rating,
    previous_purchases
):

    gender_binary = {
        "Male": 1,
        "Female": 0
    }

    if isinstance(gender, str):

        gender = gender_binary.get(
            gender,
            gender
        )

    customer = pd.DataFrame({
        "Age": [age],
        "Gender_Binary": [gender],
        "Purchase Amount (USD)": [purchase_amount],
        "Review Rating": [review_rating],
        "Previous Purchases": [previous_purchases]
    })

    prediction = best_model.predict(
        customer
    )

    return prediction[0]

# ============================================================
# 57. TEST PREDICTION FUNCTION
# ============================================================

result = predict_customer_segment(
    age=25,
    gender="Female",
    purchase_amount=60,
    review_rating=4.2,
    previous_purchases=10
)

print(
    "Predicted Customer Segment:",
    result
)

# ============================================================
# 58. FINAL PROJECT SUMMARY
# ============================================================

print("=" * 70)
print("CUSTOMER SHOPPING ANALYSIS - FINAL SUMMARY")
print("=" * 70)

# ------------------------------------------------------------
# Dataset
# ------------------------------------------------------------

print("\nDataset Shape:")
print(df.shape)

# ------------------------------------------------------------
# Clustering
# ------------------------------------------------------------

print("\nNumber of Customer Segments:")
print(SELECTED_K)

print("\nSilhouette Score for Selected K:")
selected_index = list(K_range).index(SELECTED_K)
print(round(silhouette_scores[selected_index], 4))

# ------------------------------------------------------------
# Best Classification Model
# ------------------------------------------------------------

print("\nBest Classification Model:")
print("Logistic Regression")

# ------------------------------------------------------------
# Classification Performance
# ------------------------------------------------------------

best_row = results_df[
    results_df["Model"] == "Logistic Regression"
].iloc[0]

print("\nLogistic Regression Performance:")

print(f"Accuracy : {best_row['Accuracy']:.4f}")
print(f"Precision: {best_row['Precision']:.4f}")
print(f"Recall   : {best_row['Recall']:.4f}")
print(f"F1 Score : {best_row['F1 Score']:.4f}")

# ------------------------------------------------------------
# Customer Segment Distribution
# ------------------------------------------------------------

print("\nCustomer Segment Distribution:")

display(
    segment_profile[
        ["Customer Count", "Customer %"]
    ].round(2)
)

# ------------------------------------------------------------
# Deployment Information
# ------------------------------------------------------------

print("\nDeployment:")
print("Model: Logistic Regression")
print("Model File: customer_segment_model.pkl")
print("Status: Ready for Streamlit Deployment")

print("\nFeatures Used for Prediction:")

for feature in cluster_features:
    print("-", feature)

print("\nTarget:")
print("Customer Segment")

print("\n" + "=" * 70)
print("PROJECT COMPLETED - READY FOR DEPLOYMENT")
print("=" * 70)

# ============================================================
# FINAL LOGISTIC REGRESSION MODEL FOR DEPLOYMENT
# ============================================================

import joblib
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# Features
cluster_features = [
    "Age",
    "Gender_Binary",
    "Purchase Amount (USD)",
    "Review Rating",
    "Previous Purchases"
]

X = df[cluster_features]
y = df["Customer Segment"]

# Final Logistic Regression Pipeline
final_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        max_iter=1000,
        random_state=42
    ))
])

# Train on full dataset
final_model.fit(X, y)

# Save everything needed for deployment
deployment_artifacts = {
    "model": final_model,
    "features": cluster_features,
    "target": "Customer Segment",
    "model_name": "Logistic Regression"
}

joblib.dump(
    deployment_artifacts,
    "customer_segment_model.pkl"
)

print("✅ Logistic Regression trained successfully.")
print("✅ Model saved as: customer_segment_model.pkl")
print("✅ Ready for Streamlit deployment.")

import joblib
import pandas as pd

# Load saved model
artifacts = joblib.load("customer_segment_model.pkl")

model = artifacts["model"]
features = artifacts["features"]

# New customer
new_customer = pd.DataFrame([{
    "Age": 55,
    "Gender_Binary": 0,
    "Purchase Amount (USD)": 25,
    "Review Rating": 4.5,
    "Previous Purchases": 3
}])

# Correct feature order
new_customer = new_customer[features]

# Prediction
prediction = model.predict(new_customer)

print("Predicted Customer Segment:", prediction[0])

